#!/bin/sh /etc/rc.common

START=55
STOP=15
USE_PROCD=1

PROG=/usr/bin/dns-lo-first
CONFIG=/etc/dns-lo-first/config.yaml

start_service() {
	mkdir -p /var/cache/dns-lo-first /var/log/dns-lo-first
	procd_open_instance
	procd_set_param command "$PROG" -config "$CONFIG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	procd_send_signal dns-lo-first
}
